import turtle
t=turtle.Turtle()
turtle.setup(600,600)
t.speed(10)
t.penup()
t.goto(-200,-200)
t.pendown()
t.fillcolor("white")
t.begin_fill()
for i in range(2):
 t.forward(400)
 t.left(90)
 t.forward(350)
 t.left(90)
t.end_fill()
t.fillcolor("red")
t.begin_fill()
for i in range(4):
 t.forward(150)
 t.left(90)
t.end_fill()
t.fillcolor("red")
t.begin_fill()
t.penup()
t.goto(0,-200)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for i in range(2):
 t.forward(200)
 t.left(90)
 t.forward(150)
 t.left(90)
t.end_fill()
t.penup()
t.goto(-200,0)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for i in range(4):
 t.forward(150)
 t.left(90)
t.end_fill()
t.penup()
t.goto(0,0)
t.pendown()
t.fillcolor("red")
t.begin_fill()
for i in range(2):
 t.forward(200)
 t.left(90)
 t.forward(150)
 t.left(90)
t.end_fill()
t.hideturtle()
turtle.done()